"""initial migration

Revision ID: 12493fc9fc4a
Revises: 
Create Date: 2025-05-08 12:17:03.692008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12493fc9fc4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'classes', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'rooms', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'students', 'school', ['school_id'], ['id'])
    op.create_foreign_key(None, 'users', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    # ### end Alembic commands ###
