"""umozliwienia NULL dla lesson_instance.template_id

Revision ID: 4ddcedb92a3a
Revises: 35e28601c3d8
Create Date: 2025-05-19 16:47:42.192781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ddcedb92a3a'
down_revision: Union[str, None] = '35e28601c3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_instances', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('lesson_instances_template_id_fkey', 'lesson_instances', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_instances', 'lesson_templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson_instances', type_='foreignkey')
    op.create_foreign_key('lesson_instances_template_id_fkey', 'lesson_instances', 'lesson_templates', ['template_id'], ['id'])
    op.alter_column('lesson_instances', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='schedule_class_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='schedule_room_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='schedule_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='schedule_pkey')
    )
    # ### end Alembic commands ###
