"""Fix weekday type.

Revision ID: 76abce7ff79f
Revises: 1f17291d55a7
Create Date: 2025-05-08 16:06:11.332691
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76abce7ff79f'
down_revision: Union[str, None] = '1f17291d55a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_templates', 'weekday',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="weekday::integer")  # Używamy USING do konwersji typu
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_templates', 'weekday',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
